version: '3.8'



services:

## SQL Server
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - medilabonet
## MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - medilabonet

## Patient Service
  patientservice:
    image: patientservice:latest
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "8081:8080"
      
    environment:  
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - JwtSettings__Issuer=${JwtSettings_Issuer}
      - JwtSettings__Audience=${JwtSettings_Audience}
      - JwtSettings__SecretKey=${JwtSettings_SecretKey}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings_DefaultConnection}
    depends_on:
      - sqlserver  
    networks:
      - medilabonet
## Patient Notes Service
  patientnotes:
    image: patientnotes:latest
    build:
      context: .
      dockerfile: PatientNotes/Dockerfile
    ports:
      - "8091:8090"
      
    environment:
      - MedilaboNotesData__ConnectionString=${MedilaboNotesData_ConnectionString}
      - MedilaboNotesData__DatabaseName=${MedilaboNotesData_DatabaseName}
      - MedilaboNotesData__CollectionName=${MedilaboNotesData_CollectionName}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - JwtSettings__Issuer=${JwtSettings_Issuer}
      - JwtSettings__Audience=${JwtSettings_Audience}
      - JwtSettings__SecretKey=${JwtSettings_SecretKey}
    depends_on:
      - mongodb
    networks:
      - medilabonet

## Gateway
  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "5000:5000"
      
    environment: 
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - JwtSettings__Issuer=${JwtSettings_Issuer}
        - JwtSettings__Audience=${JwtSettings_Audience}
        - JwtSettings__SecretKey=${JwtSettings_SecretKey}
        - AllowedOrigins__0=${AllowedOrigins_0}
        - AllowedOrigins__1=${AllowedOrigins_1}
        - AllowedOrigins__2=${AllowedOrigins_2}
        - AllowedOrigins__3=${AllowedOrigins_3}
        - AllowedOrigins__4=${AllowedOrigins_4}      


    depends_on:
      - patientservice
      - patientnotes
    networks:
      - medilabonet

## Diabete Risk Report Service
  diabeteriskreportservice:
    image: diabeteriskreportservice:latest
    build:
      context: .
      dockerfile: DiabeteRiskReportService/Dockerfile
    ports:
      - "5021:5020"
      
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - JwtSettings__Issuer=${JwtSettings_Issuer}
      - JwtSettings__Audience=${JwtSettings_Audience}
      - JwtSettings__SecretKey=${JwtSettings_SecretKey}
      - GatewayUrl=${GatewayUrl}
    
    depends_on:
      - gateway
      - patientservice
      - patientnotes 
    networks:
      - medilabonet

## Frontend Razor
  frontendrazor:
    image: frontendrazor:latest
    build:
      context: .
      dockerfile: FrontendRazor/Dockerfile
    ports:
      - "5011:5010"
      
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - GatewayUrl=${GatewayUrl}
    depends_on:
      - gateway
    networks:
      - medilabonet

##volumes
volumes:
  sqlserver_data:
  mongo_data:

  ##networks
networks:
  medilabonet:
    name: medilabonet
    driver: bridge
