version: '3.8'

x-common-env: &common-env
  - ASPNETCORE_ENVIRONMENT=Development
  - JwtSettings__Issuer=YourIssuer
  - JwtSettings__Audience=YourAudience
  - JwtSettings__SecretKey=LeGrandSecretencorePlusplusLong!!!

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - medilabonet

  patientservice:
    image: patientservice:latest
    build:
      context: .
      dockerfile: MedilaboSolutions/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Issuer=YourIssuer
      - JwtSettings__Audience=YourAudience
      - JwtSettings__SecretKey=LeGrandSecretencorePlusplusLong!!!
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PatientDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - sqlserver  
    networks:
      - medilabonet

  patientnotes:
    image: patientnotes:latest
    build:
      context: .
      dockerfile: PatientNotes/Dockerfile
    ports:
      - "8090:8090"
      - "8091:8091"
    environment: *common-env    
    networks:
      - medilabonet

  gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment: *common-env
    depends_on:
      - patientservice
      - patientnotes
    networks:
      - medilabonet

  diabeteriskreportservice:
    image: diabeteriskreportservice:latest
    build:
      context: .
      dockerfile: DiabeteRiskReportService/Dockerfile
    ports:
      - "5020:5020"
      - "5021:5021"
    environment: *common-env
    depends_on:
      - gateway
      - patientservice
      - patientnotes 
    networks:
      - medilabonet

  frontendrazor:
    image: frontendrazor:latest
    build:
      context: .
      dockerfile: FrontendRazor/Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    environment: *common-env
    depends_on:
      - gateway
    networks:
      - medilabonet

volumes:
  sqlserver_data:

networks:
  medilabonet:
    name: medilabonet
    driver: bridge
