services:

#sqlserverDb 
 sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=UnBonMotDePasse123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - reseau

#mongoDB
 mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - reseau

#Gateway
#PatientService
 patientservice:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    container_name: patientservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PatientDb;User Id=sa;Password=UnBonMotDePasse123!
      - JwtSettings__Issuer=YourIssuer
      - JwtSettings__Audience=YourAudience
      - JwtSettings__SecretKey=LeGrandSecretencorePlusplusLong!!!
    ports:
      - "8000:80"
      - "8001:443"
    networks:
      - reseau
    depends_on:
      - sqlserver

#PatientNotes
#DiabeteRiskReportService
#FrontendRazor
 frontendrazor:
    build:
      context: .
      dockerfile: FrontendRazor/Dockerfile
    container_name: frontendrazor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
    networks:
      - reseau
    depends_on:
      - sqlserver

networks:
  reseau:

volumes:
  sql_data:
  mongo_data: