@Gateway_HostAddress = http://localhost:5000

### Connexion
POST {{Gateway_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "organisateur",
  "password": "Organisateur@123"
}

### Déconnexion
POST {{Gateway_HostAddress}}/auth/logout
Accept: application/json

### Obtenir tous les patients
GET {{Gateway_HostAddress}}/patient
Accept: application/json

### Obtenir un patient par ID
GET {{Gateway_HostAddress}}/patient/1
Accept: application/json

### Modifier un patient
POST {{Gateway_HostAddress}}/patient/Edit/1
Content-Type: application/json

{
  "id": 1,
  "nom": "John",
  "prenom": "Doe",
  "dateDeNaissance": "1980-01-01",
  "genre": "Male",
  "adresse": "123 Main St",
  "telephone": "123-456-7890"
}

###
